select * from category;

SELECT FILM.TITLE AS FILM_NAME , CATEGORY.NAME AS CATEGORY_NAME , LANGUAGE.NAME AS LANGUAGE_NAME FROM CATEGORY
JOIN
FILM_CATEGORY
ON
CATEGORY.CATEGORY_ID = FILM_CATEGORY.CATEGORY_ID
JOIN
FILM
ON
FILM_CATEGORY.FILM_ID = FILM.FILM_ID
JOIN
LANGUAGE
ON
FILM.LANGUAGE_ID = LANGUAGE.LANGUAGE_ID
WHERE
CATEGORY.NAME = 'Horror'
AND
LANGUAGE.NAME = 'English'
AND
(FILM.TITLE LIKE '%Devil%' OR FILM.TITLE LIKE '%devil%' OR FILM.TITLE LIKE '%Ghost%' OR FILM.TITLE LIKE '%ghost%')
ORDER BY FILM.TITLE ASC
LIMIT 10;

